[meta]
name = "Just Another Queue Tool"
author = "Ezio"
category = "Matchmaking"
version = "0.1.6"
siteid = 758

[script]
dependencies = [ "NadeoServices" ]
export_dependencies = [ "NadeoServices" ]
exports = [ "src/Export.as" ]
module = "JAQT"
shared_exports = [ "src/ExportShared" ]
