[meta]
name = "Simple Ranked"
author = "Ezio"
category = "Matchmaking"
version = "0.1.4"
siteid = 758

[script]
dependencies = [ "NadeoServices" ]
export_dependencies = [ "NadeoServices" ]
exports = [ "src/Export.as" ]
module = "SimpleRanked"
shared_exports = [ "src/ExportShared" ]
